OBJS_NOKIA5110 := nokia5110 nokia5110_console test

OBJS_NOKIA5110 := $(addprefix drivers/nokia5110/, $(OBJS_NOKIA5110))
OBJS_NOKIA5110 := $(addsuffix .o, $(OBJS_NOKIA5110))

$(info OBJS_NOKIA5110: $(OBJS_NOKIA5110))
