#pragma once

#define USB_CLK_30_60MHZ 0
#define USB_CLK_48MHZ    1
#define USB_CLK_6MHZ     2

#define USB_DEVICE_ROOT_HUB_NUMBER 0

#define USB_RECV_FIFO_SIZE         20480
#define USB_NON_PERIODIC_FIFO_SIZE 20480
#define USB_PERIODIC_FIFO_SIZE     20480

#define BCM2835_USB_NUM_CHANNELS 8

#define USB_MAX_INTERFACES_PER_DEVICE 8
#define USB_MAX_ENDPOINTS_PER_DEVICE 16

#define USB_CONTROL_MSG_TIMEOUT_MS 10

#define USB_ROOT_HUB_STRING_IDX_PRODUCT      1
#define USB_ROOT_HUB_STRING_IDX_MANUFACTURER 2
#define USB_ROOT_HUB_STRING_IDX_SERIAL       3
#define USB_ROOT_HUB_STRING_PRODUCT u"bcm2835_root_hub"
#define USB_ROOT_HUB_STRING_MANUFACTURER u"broadcom"
#define USB_ROOT_HUB_STRING_SERIAL u"seri"

#define USB_SPEC_2_0 0x200
#define USB_DEV_RELEASE_NUM 0x100

