#pragma once

#define USB_CLK_30_60MHZ 0
#define USB_CLK_48MHZ    1
#define USB_CLK_6MHZ     2

#define USB_DEVICE_ROOT_HUB_NUMBER 0

#define USB_RECV_FIFO_SIZE         20480
#define USB_NON_PERIODIC_FIFO_SIZE 20480
#define USB_PERIODIC_FIFO_SIZE     20480

#define BCM2835_USB_NUM_CHANNELS 8

#define USB_MAX_INTERFACES_PER_DEVICE 8
#define USB_MAX_ENDPOINTS_PER_DEVICE 16

#define USB_CONTROL_MSG_TIMEOUT_MS 10
