#pragma once

#define USB_DEVICE_ROOT_HUB_NUMBER 0

#define USB_RECV_FIFO_SIZE         20480
#define USB_NON_PERIODIC_FIFO_SIZE 20480
#define USB_PERIODIC_FIFO_SIZE     20480

#define BCM2835_USB_NUM_CHANNELS 8


#define USB_CONTROL_MSG_TIMEOUT_MS 10
