DIR=cmdrunner

OBJS_CMDRUNNER := cmdrunner f5161ah memdump ls help gpio mbox pwm clock shiftreg spi max7219 nokia5110

OBJS_CMDRUNNER := $(addsuffix .o, $(addprefix $(DIR)/, $(OBJS_CMDRUNNER)))

$(info OBJS_CMDRUNNER = $(OBJS_CMDRUNNER))
