DIR=cmdrunner

OBJS_CMDRUNNER := memdump
OBJS_CMDRUNNER += ls
OBJS_CMDRUNNER += help
OBJS_CMDRUNNER += cmdrunner

OBJS_CMDRUNNER := $(addsuffix .o, $(addprefix $(DIR)/, $(OBJS_CMDRUNNER)))

$(info OBJS_CMDRUNNER = $(OBJS_CMDRUNNER))
