OBJS_ARMV8 = mmu.o armv8.o armv8_timer.o start.o cpu_context.o armv8_cpu.o armv8_lock.o
$(info OBJS_ARMV8 $(OBJS_ARMV8))

OBJS_ARMV8 := $(addprefix arch/armv8/, $(OBJS_ARMV8))

# arch/armv8/armv8.o: arch/armv8/armv8.S
#	$(CC) $(CFLAGS) -c $? -o $@ 

